### ISSUE TITLE
项目启动正常，浏览器进入管理页面报错

### ISSUE THREAD

**Issue by lixingmao** [jhao104/SSDBAdmin#19]
python 环境：3.7.2
redis 版本： 5.0.4 (00000000/0) 64 bit

AttributeError
AttributeError: 'int' object has no attribute 'decode'

Traceback (most recent call last)
File "/Users/lixingmao/Downloads/proxy_pool/venv/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/lixingmao/Downloads/proxy_pool/venv/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/Users/lixingmao/Downloads/proxy_pool/venv/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/lixingmao/Downloads/proxy_pool/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/Users/lixingmao/Downloads/proxy_pool/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/Users/lixingmao/Downloads/proxy_pool/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/lixingmao/Downloads/proxy_pool/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/Users/lixingmao/Downloads/proxy_pool/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/Users/lixingmao/Downloads/proxy_pool/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/lixingmao/Downloads/proxy_pool/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
Open an interactive python shell in this framereturn self.view_functions[rule.endpoint](**req.view_args)
File "/Users/lixingmao/Downloads/SSDBAdmin/SSDBAdmin/apps/index.py", line 34, in index
server_info = SSDBClient(request).serverInfo()
File "/Users/lixingmao/Downloads/SSDBAdmin/SSDBAdmin/model/SSDBClient.py", line 53, in serverInfo
info_list = [_.decode() for _ in self.__conn.execute_command('info')]
File "/Users/lixingmao/Downloads/SSDBAdmin/SSDBAdmin/model/SSDBClient.py", line 53, in <listcomp>
info_list = [_.decode() for _ in self.__conn.execute_command('info')]
AttributeError: 'int' object has no attribute 'decode'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

**Comment by jhao104** [comment]
这是ssdb的工具 不是redis
