### ISSUE TITLE
运行成功，网页报错

### ISSUE THREAD

**Issue by Warm-rain** [jhao104/SSDBAdmin#20]
python 3.7.1
flask 0.12

`Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Downloads\goole\SSDBAdmin-master\SSDBAdmin\apps\index.py", line 34, in index
    server_info = SSDBClient(request).serverInfo()
  File "D:\Downloads\goole\SSDBAdmin-master\SSDBAdmin\model\SSDBClient.py", line 51, in serverInfo
    info_list = [_.decode() for _ in self.__conn.execute_command('info')]
  File "D:\Downloads\goole\SSDBAdmin-master\SSDBAdmin\model\SSDBClient.py", line 51, in <listcomp>
    info_list = [_.decode() for _ in self.__conn.execute_command('info')]
AttributeError: 'int' object has no attribute 'decode'`

![image](https://user-images.githubusercontent.com/31696282/57267790-e41be100-70b3-11e9-8d31-668f6fb8b771.png)
![image](https://user-images.githubusercontent.com/31696282/57267776-d6fef200-70b3-11e9-8913-c6ad459f7af0.png)

**Comment by Lunpopo** [comment]
兄弟，这是SSDB的可视化工具，不是Redis的哦
