### ISSUE TITLE
能够访问SSDBAdmin但是无法获取SSDB数据

### ISSUE THREAD

**Issue by diyhome** [jhao104/SSDBAdmin#27]
如题
Web网页提示:`500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.`
服务器的运行日志里面有一个报错:`AttributeError: 'list' object has no attribute 'decode`

服务器环境:`Centos 8` && `python36`

**Comment by FrankWasHello** [comment]
我也是这个问题，不知道是什么情况，求大神解答
![image](https://github.com/jhao104/SSDBAdmin/assets/34059274/a19bdd7c-7423-41fe-9837-b2567a907014)

**Comment by FrankWasHello** [comment]
以下为报错信息：
[2023-06-06 17:06:03,207] ERROR in app: Exception on /ssdbadmin/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/Desktop/OtherProject/SSDBAdmin/SSDBAdmin/apps/index.py", line 34, in index
    server_info = SSDBClient(request).serverInfo()
  File "/Users/Desktop/OtherProject/SSDBAdmin/SSDBAdmin/model/SSDBClient.py", line 52, in serverInfo
    version = info_list[2]
IndexError: list index out of range

**Comment by jhao104** [comment]
ssdb版本发下

**Comment by FrankWasHello** [comment]
![image](https://github.com/jhao104/SSDBAdmin/assets/34059274/785eaad0-7f9b-442c-8817-97feec721d16)

**Comment by jhao104** [comment]
没复现出来，你可以试试把这一行print出来看看是什么
``
File "/Users/Desktop/OtherProject/SSDBAdmin/SSDBAdmin/model/SSDBClient.py", line 52, in serverInfo
version = info_list[2]
``
加个print info_list.  这里预期是个版本信息的列表。版本号在第三个位置

**Comment by FrankWasHello** [comment]
感觉应该是redis的问题。。
